image: docker:20.10.5

services:
  - docker:20.10.5-dind

stages:
  - build-latest
  - build-tag

variables:
  YA_REGISTRY_LOGIN: oauth
  YA_REGISTRY: cr.yandex
  YA_REGISTRY_ID: crpdgkjqba4kiu6sm7bq
  IMAGE_NAME: netology-web

builder:latest:
  stage: build-latest
  script:
    - docker logout
    - docker login -u $YA_REGISTRY_LOGIN -p $YA_REGISTRY_PASSWORD $YA_REGISTRY
    - docker build -t $YA_REGISTRY/$YA_REGISTRY_ID/$IMAGE_NAME:latest .
    - docker push $YA_REGISTRY/$YA_REGISTRY_ID/$IMAGE_NAME:latest
  rules:
    - if: '$CI_COMMIT_TAG == null'
      changes:
        - Dockerfile
        - html/*
        - .gitlab-ci.yml

builder:tag:
  stage: build-tag
  script:
    - docker logout
    - docker login -u $YA_REGISTRY_LOGIN -p $YA_REGISTRY_PASSWORD $YA_REGISTRY
    - docker build -t $YA_REGISTRY/$YA_REGISTRY_ID/$IMAGE_NAME:$CI_COMMIT_TAG .
    - docker push $YA_REGISTRY/$YA_REGISTRY_ID/$IMAGE_NAME:$CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG
      changes:
        - Dockerfile
        - html/*
        - .gitlab-ci.yml
