image: docker:20.10.5

services:
  - docker:20.10.5-dind
  - registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image

stages:
  - build
  - deploy

variables:
  YA_REGISTRY_LOGIN: oauth
  YA_REGISTRY: cr.yandex
  YA_REGISTRY_ID: crpdgkjqba4kiu6sm7bq
  IMAGE_NAME: netology-web
  KUBE_URL: https://158.160.168.73


before_script:
    - docker login -u $YA_REGISTRY_LOGIN -p $YA_REGISTRY_PASSWORD $YA_REGISTRY


.kubectl:
  stage: deploy
  script:
    - kubectl config set-cluster k8s --certificate-authority=ca.pem --server=$KUBE_URL
    - kubectl config set-credentials admin-user --token=$KUBE_TOKEN
    - kubectl config set-context default --cluster=k8s --user=admin-user
    - kubectl config use-context default
    - kubectl get po

builder_latest:
  stage: build
  script:
    - docker build -t $YA_REGISTRY/$YA_REGISTRY_ID/$IMAGE_NAME:latest .
    - docker push $YA_REGISTRY/$YA_REGISTRY_ID/$IMAGE_NAME:latest
  rules:
    - if: '$CI_COMMIT_TAG == null'
      changes:
        - Dockerfile
        - html/*

builder_tag:
  extends: 
    - .kubectl
  stage: deploy
  script:
    - docker build -t $YA_REGISTRY/$YA_REGISTRY_ID/$IMAGE_NAME:$CI_COMMIT_TAG .
    - docker push $YA_REGISTRY/$YA_REGISTRY_ID/$IMAGE_NAME:$CI_COMMIT_TAG
    - sed -i -e "s/IMAGE_TAG/$CI_COMMIT_TAG/" deployment-nginx.yaml
    - kubectl apply -f deployment-nginx.yaml 
  rules:
    - if: $CI_COMMIT_TAG
      changes:
        - Dockerfile
        - html/*
