image: docker:20.10.5

services:
  - docker:20.10.5-dind

stages:
  - build
  - deploy

variables:
  YA_REGISTRY_LOGIN: oauth
  YA_REGISTRY: cr.yandex
  YA_REGISTRY_ID: crpdgkjqba4kiu6sm7bq
  IMAGE_NAME: netology-web
  K8S_REP: "https://$CI_REGISTRY_USER:$CI_JOB_TOKEN@gitlab.com/$CI_PROJECT_NAMESPACE/diplom.git"

.builder:
  script:
    - docker login -u $YA_REGISTRY_LOGIN -p $YA_REGISTRY_PASSWORD $YA_REGISTRY
    - docker build -t $YA_REGISTRY/$YA_REGISTRY_ID/$IMAGE_NAME:$TAG .
    - docker push $YA_REGISTRY/$YA_REGISTRY_ID/$IMAGE_NAME:$TAG
  rules:
    - changes:
        - Dockerfile
        - html/*

builder_latest:
  stage: build
  extends: .builder
  variables:
    TAG: latest
  rules:
    - if: '$CI_COMMIT_TAG == null'

builder_tag:
  stage: build
  extends: .builder
  variables:
    TAG: $CI_COMMIT_TAG
  rules:
    - if: $CI_COMMIT_TAG
      
deploy:
  stage: deploy
  image: "registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image"
  script:
    - K8S_MASTER_IP=$(<k8s-master-external-ip.txt)
    - kubectl config set-cluster k8s --certificate-authority=$CERTIFICATE_K8S --server=$K8S_MASTER_IP
    - kubectl config set-credentials admin-user --token=$KUBE_TOKEN
    - kubectl config set-context default --cluster=k8s --user=admin-user
    - kubectl config use-context default
    - mkdir /test && cd /test
    - git init
    - git remote add k8s $K8S_REP
    - git pull k8s master
    - sed -i -e "s/IMAGE_TAG/$CI_COMMIT_TAG/" k8s/deployment-nginx.yaml
    - kubectl apply -f k8s/deployment-nginx.yaml 
  rules:
    - if: $CI_COMMIT_TAG
      changes:
        - Dockerfile
        - html/*
