{
 "title": "Kubernetes dashboard",
 "tags": [ "kubernetes-mixin" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job5",
    "query": {
     "query": "label_values(grafana_build_info,job)"
    }
   },
   {
    "name": "instance5",
    "query": {
     "query": "label_values(grafana_build_info,instance5)"
    }
   },
   {
    "name": "cluster",
    "query": {
     "query": "label_values(node_time_seconds,cluster)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values(node_exporter_build_info{job=\"node-exporter\", cluster=\"$cluster\"},instance)"
    }
   },
   {
    "name": "cluster3",
    "query": {
     "query": "label_values(up{job=\"kubelet\", metrics_path=\"/metrics\"},cluster3)"
    }
   },
   {
    "name": "instance3",
    "query": {
     "query": "label_values(up{job=\"kubelet\", metrics_path=\"/metrics\",cluster=\"$cluster3\"},instance3)"
    }
   },
   {
    "name": "cluster4",
    "query": {
     "query": "label_values(up{job=\"kube-state-metrics\"},cluster4)"
    }
   },
   {
    "name": "node4",
    "query": {
     "query": "label_values(kube_node_info{cluster=\"$cluster4\"},node4)"
    }
   },
   {
    "name": "node2",
    "query": "netology-k8s-node-esih-cl13hivh5h6ela15k0vg"
   },
   {
    "name": "node1",
    "query": "netology-k8s-node-azin-cl1ovuucufbkbd0ioqku"
   },
   {
    "name": "node3",
    "query": "netology-k8s-node-odyp-cl15hk84bj4srvttr30c"
   }
  ]
 },
 "panels": [
  {
   "title": "API Availability (30d)",
   "type": "stat",
   "description": "How many percent of requests (both read and write) in 30 days have been answered successfully and fast enough?",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "apiserver_request:availability30d{verb=\"all\", cluster=\"\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "timeseries",
   "description": "HTTP status",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum by (status_code) (irate(grafana_http_request_duration_seconds_count{job=~\"$job5\", instance=~\"$instance5\"}[1m])) ",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Operation Rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "ops" }
   ],
   "targets": [
    {
     "expr": "sum(rate(kubelet_runtime_operations_total{cluster=\"\",job=\"kubelet\", metrics_path=\"/metrics\",instance=~\"(192\\\\.168\\\\.10\\\\.12:10250|192\\\\.168\\\\.20\\\\.15:10250|192\\\\.168\\\\.30\\\\.32:10250)\"}[$__rate_interval])) by (operation_type, instance)",
     "legendFormat": "{{instance}} {{operation_type}}"
    }
   ]
  },
  {
   "title": "Node 1 CPU Utilisation",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m{job=\"node-exporter\", instance=\"$node1\", cluster=\"\"} != 0",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Node 1 Memory Utilisation",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio{job=\"node-exporter\", instance=\"$node1\", cluster=\"\"} != 0",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Node 1 Disk Space Utilisation",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(1 -\n  (\n   max without (mountpoint, fstype) (node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"\", instance=\"$node1\", cluster=\"\"})\n   /\n   max without (mountpoint, fstype) (node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", instance=\"$node1\", cluster=\"\"})\n  ) != 0\n)\n",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Node 1 CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"$cluster4\", node=~\"$node1\", resource=\"cpu\"})",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster4\", node=~\"$node1\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Node 2 CPU Utilisation",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m{job=\"node-exporter\", instance=\"$node2\", cluster=\"\"} != 0",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Node 2 Memory Utilisation",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio{job=\"node-exporter\", instance=\"$node2\", cluster=\"\"} != 0",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Node 2 Disk Space Utilisation",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(1 -\n  (\n   max without (mountpoint, fstype) (node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"\", instance=\"$node2\", cluster=\"\"})\n   /\n   max without (mountpoint, fstype) (node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", instance=\"$node2\", cluster=\"\"})\n  ) != 0\n)\n",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Node 2 CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"$cluster4\", node=~\"$node2\", resource=\"cpu\"})",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster4\", node=~\"$node2\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Node 3 CPU Utilisation",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:node_cpu_utilisation:rate5m{job=\"node-exporter\", instance=\"$node3\", cluster=\"\"} != 0",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Node 3 Memory Utilisation",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "instance:node_memory_utilisation:ratio{job=\"node-exporter\", instance=\"$node3\", cluster=\"\"} != 0",
     "legendFormat": "Utilisation"
    }
   ]
  },
  {
   "title": "Node 3 Disk Space Utilisation",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(1 -\n  (\n   max without (mountpoint, fstype) (node_filesystem_avail_bytes{job=\"node-exporter\", fstype!=\"\", instance=\"$node3\", cluster=\"\"})\n   /\n   max without (mountpoint, fstype) (node_filesystem_size_bytes{job=\"node-exporter\", fstype!=\"\", instance=\"$node3\", cluster=\"\"})\n  ) != 0\n)\n",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Node 3 CPU Usage",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_node_status_capacity{cluster=\"$cluster4\", node=~\"$node3\", resource=\"cpu\"})",
     "legendFormat": "max capacity"
    },
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{cluster=\"$cluster4\", node=~\"$node3\"}) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}